CREATE OR REPLACE PACKAGE BODY ONLINE_STORE AS

    PROCEDURE REGION_INS(ID REGIONS.REGION_ID%TYPE,
                         NAME REGIONS.REGION_NAME%TYPE)IS
      L_ERROR   EXCEPTION;
    BEGIN
      
      INSERT INTO REGIONS VALUES(ID,NAME);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN REGION...RETRY');
        RAISE L_ERROR;  
    END REGION_INS;

    PROCEDURE COUNTRY_INS(ID COUNTRYS.COUNTRY_ID%TYPE,
                          NAME COUNTRYS.COUNTRY_NAME%TYPE)IS
      L_ERROR   EXCEPTION;
    BEGIN
      
      INSERT INTO COUNTRYS VALUES(ID,NAME);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN COUNTRY...RETRY');
        RAISE L_ERROR;  
    END COUNTRY_INS;

    PROCEDURE PROD_CATEGORYS_INS(ID PROD_CATEGORYS.CAT_ID%TYPE,
                                 NAME PROD_CATEGORYS.CATEGORY_NAME%TYPE)IS
      L_ERROR   EXCEPTION;
    BEGIN
      
      INSERT INTO PROD_CATEGORYS VALUES(ID,NAME);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN PROD CATEGORY...RETRY');
        RAISE L_ERROR;  
    END PROD_CATEGORYS_INS;

    PROCEDURE LOCATION_INS(ID LOCATIONS.LOCATION_ID%TYPE,
                           ADD   LOCATIONS.ADDRESS%TYPE,
                           PC   LOCATIONS.POSTAL_CODE%TYPE,
                           CITY   LOCATIONS.CITY%TYPE,
                           STATE   LOCATIONS.STATE%TYPE,
                           CID   LOCATIONS.COUNTRY_ID%TYPE
                              )IS
    L_ERROR   EXCEPTION;                                                        
    BEGIN
      INSERT INTO LOCATIONS VALUES(ID,ADD,PC,CITY,STATE,CID);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN LOCATION...RETRY');
        RAISE L_ERROR;  
    END LOCATION_INS;

    PROCEDURE WAREHOUSES_INS(ID WAREHOUSES.WAREHOUSE_ID%TYPE,
                             NAME   WAREHOUSES.WAREHOUSENAME%TYPE,
                              LID  WAREHOUSES.LOCATION_ID%TYPE
                                 )IS
    L_ERROR   EXCEPTION;
    BEGIN
     INSERT INTO WAREHOUSES VALUES(ID,NAME,LID);
      
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN WAREHOUSE...RETRY');
        RAISE L_ERROR; 
    END WAREHOUSES_INS;

    PROCEDURE DEP_INS(ID DEPARTMENTS.DEPT_ID%TYPE,
                             NAME   DEPARTMENTS.DEPT_NAME%TYPE,
                              LID  DEPARTMENTS.LOCATION_ID%TYPE
                                 )IS
    L_ERROR   EXCEPTION;
    BEGIN
     INSERT INTO DEPARTMENTS VALUES(ID,NAME,LID);
      
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN DEPARTMENT...RETRY');
        RAISE L_ERROR;  
    END DEP_INS;     


    PROCEDURE EMPLOYEES_INS(ID EMPLOYEES.EMP_ID%TYPE,
                        FNAME EMPLOYEES.FIRSTNAME%TYPE,
                        LNAME EMPLOYEES.LASTNAME%TYPE,
                        MAIL EMPLOYEES.EMAIL%TYPE,
                        PHONE EMPLOYEES.PHONE%TYPE,
                        HDATE EMPLOYEES.HIREDATE%TYPE,
                        DOB EMPLOYEES.DOB%TYPE,
                        SAL EMPLOYEES.SALARY%TYPE,
                        MGR EMPLOYEES.MANAGER%TYPE,
                        DES EMPLOYEES.DESIGNATION%TYPE,
                         DID EMPLOYEES.DEPT_ID%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      INSERT INTO EMPLOYEES VALUES(ID,FNAME,LNAME,MAIL,PHONE,HDATE,DOB,SAL,MGR,DES,DID);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN EMPLOYEE...RETRY');
        RAISE L_ERROR;  
    END EMPLOYEES_INS;                       



    PROCEDURE CUSTOMERS_INS(ID CUSTOMERS.CUST_ID%TYPE,
                             NAME CUSTOMERS.CUST_NAME%TYPE,
                             ADD CUSTOMERS.ADDRESS%TYPE,
                             WS CUSTOMERS.WEBSITE%TYPE,
                             FACE CUSTOMERS.FACEBOOK%TYPE,
                             TWIT CUSTOMERS.TWITTER%TYPE,
                              WAPP CUSTOMERS.WHATSAPP%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      INSERT INTO CUSTOMERS VALUES(ID,NAME,ADD,WS,FACE,TWIT,WAPP);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN CUSTOMER...RETRY');
        RAISE L_ERROR;  
    END CUSTOMERS_INS; 

    PROCEDURE CONTACTS_INS(ID CUST_CONTACTS.CONT_ID%TYPE,
                           FNAME   CUST_CONTACTS.FIRSTNAME%TYPE,
                           LNAME   CUST_CONTACTS.LASTNAME%TYPE,
                           EMAIL   CUST_CONTACTS.EMAIL%TYPE,
                           PHONE   CUST_CONTACTS.PHONE%TYPE,
                            CID  CUST_CONTACTS.CUST_ID%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      INSERT INTO CUST_CONTACTS VALUES(ID,FNAME,LNAME,EMAIL,PHONE,CID);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN CONTACTS...RETRY');
        RAISE L_ERROR;  
    END CONTACTS_INS; 

    PROCEDURE PRODUCTS_INS(ID PRODUCTS.PROD_ID%TYPE,
                           NAME   PRODUCTS.PROD_NAME%TYPE,
                           DESCR   PRODUCTS.DESCRIPTION%TYPE,
                           SCOST   PRODUCTS.STANDARDCOST%TYPE,
                           LPRICE   PRODUCTS.LISTPRICE%TYPE,
                           INV   PRODUCTS.INVENTORY%TYPE,
                            CID PRODUCTS.CAT_ID%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      INSERT INTO PRODUCTS VALUES(ID,NAME,DESCR,SCOST,LPRICE,INV,CID);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN PRODUCT...RETRY');
        RAISE L_ERROR;  
    END PRODUCTS_INS; 

    PROCEDURE ORDERSS_INS(ID ORDERSS.ORDER_ID%TYPE,
                          CID   ORDERSS.CUST_ID%TYPE,
                          STATUS   ORDERSS.STATUS%TYPE,
                           EID  ORDERSS.EMP_ID%TYPE,
                            ODATE ORDERSS.ORDER_DATE%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      INSERT INTO ORDERSS VALUES(ID,CID,STATUS,EID,ODATE);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN ORDERS...RETRY');
      RAISE L_ERROR;
    END ORDERSS_INS; 

    PROCEDURE ORDER_ITEMS_INS(ID ORDER_ITEMS.ORDER_ID%TYPE,
                              PID   ORDER_ITEMS.PROD_ID%TYPE,
                              QUAN   ORDER_ITEMS.QUANTITY%TYPE,
                              UPRICE   ORDER_ITEMS.UNITPRICE%TYPE,
                              WID   ORDER_ITEMS.WAREHOUSE_ID%TYPE
                              )IS
    L_ERROR   EXCEPTION;
    BEGIN
      
      INSERT INTO ORDER_ITEMS VALUES(ID,PID,QUAN,UPRICE,WID);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('DATA ENTERED IS NOT CORRECT IN ORDER_ITEMS...RETRY');
        RAISE L_ERROR;
    END ORDER_ITEMS_INS; 

END ONLINE_STORE;
/
