
CREATE TABLE REGION
(
  REGION_ID   VARCHAR2(3),
  REGION_NAME VARCHAR2(105)
)
/
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE REGION
  ADD CONSTRAINT REGION_PK PRIMARY KEY (REGION_ID)
 /
CREATE SYNONYM REGIONS FOR REGION
/

CREATE TABLE COUNTRY 
  (COUNTRY_ID 	VARCHAR2(3), 
   COUNTRY_NAME VARCHAR2(105),
CONSTRAINT COUNTRY_PK PRIMARY KEY (COUNTRY_ID))
/
CREATE SYNONYM COUNTRYS FOR COUNTRY;

CREATE TABLE LOCATION 
	(LOCATION_ID 	VARCHAR2(3), 
	 ADDRESS 		VARCHAR2(105),
	 POSTAL_CODE 	VARCHAR2(8), 
	 CITY 			VARCHAR2(70) , 
	 STATE 			VARCHAR2(70) ,
	 COUNTRY_ID 	VARCHAR2(70),
CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID) ,
CONSTRAINT FK_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID) );

CREATE SYNONYM LOCATIONS FOR LOCATION;

CREATE TABLE WAREHOUSE 
	(WAREHOUSE_ID 	VARCHAR2(3), 
	 WAREHOUSENAME 	VARCHAR2(105), 
	 LOCATION_ID 	VARCHAR2(3),
CONSTRAINT PK_WAREHOUSES PRIMARY KEY (WAREHOUSE_ID),
CONSTRAINT FK_WARE_LOC FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID) );

CREATE SYNONYM WAREHOUSES FOR WAREHOUSE;


CREATE TABLE DEPARTMENT 
	(DEPT_ID 	VARCHAR2(3) , 
	 DEPT_NAME 	VARCHAR2(105), 
	 LOCATION_ID VARCHAR2(3),
CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPT_ID),
CONSTRAINT FK_DEPT_LOC FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID));

CREATE SYNONYM DEPARTMENTS FOR DEPARTMENT;

CREATE TABLE PROD_CATEGORY 
	(CAT_ID 	VARCHAR2(4), 
	CATEGORY_NAME VARCHAR2(105),
CONSTRAINT PK_PRD_CAT PRIMARY KEY (CAT_ID)); 

CREATE SYNONYM PROD_CATEGORYS FOR PROD_CATEGORY; 


CREATE TABLE EMPLOYEE 
	(EMP_ID 	VARCHAR2(10),
	 FIRSTNAME 	VARCHAR2(105) ,
	 LASTNAME 	VARCHAR2(105),
	 EMAIL 		VARCHAR2(105), 
	 PHONE 		VARCHAR2(15),
	 HIREDATE 	DATE ,
	 DOB 		DATE ,
	 SALARY 	NUMBER(20,2), 
	 MANAGER 	VARCHAR2(10),
	 DESIGNATION VARCHAR2(105),
	 DEPT_ID 	VARCHAR2(3),
CONSTRAINT PK_EMP PRIMARY KEY (EMP_ID),
CONSTRAINT FK_EMP_LOC FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID));

CREATE SYNONYM EMPLOYEES FOR EMPLOYEE;


CREATE TABLE CUSTOMER 
	(CUST_ID VARCHAR2(10),
	CUST_NAME VARCHAR2(105), 
	ADDRESS VARCHAR2(105),
	WEBSITE VARCHAR2(105), 
	FACEBOOK VARCHAR2(105), 
	TWITTER VARCHAR2(105), WHATSAPP VARCHAR2(15),
CONSTRAINT PK_CUST PRIMARY KEY (CUST_ID));

CREATE SYNONYM CUSTOMERS FOR CUSTOMER;

CREATE TABLE CUST_CONTACT 
	(CONT_ID 	VARCHAR2(10), 
	 FIRSTNAME 	VARCHAR2(105), 
	 LASTNAME 	VARCHAR2(105),
	 EMAIL 		VARCHAR2(105), 
	 PHONE 		VARCHAR2(15), 
	 CUST_ID 	VARCHAR2(10),
CONSTRAINT PK_CUST_CONT PRIMARY KEY (CONT_ID),
CONSTRAINT FK_CUST_CONT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID));

CREATE SYNONYM CUST_CONTACTS FOR CUST_CONTACT;


CREATE TABLE PRODUCT 
	(PROD_ID 		VARCHAR2(10), 
	 PROD_NAME 		VARCHAR2(105), 
	 DESCRIPTION 	VARCHAR2(500), 
	 STANDARDCOST 	NUMBER(20,2), 
	 LISTPRICE 		NUMBER(20,2), 
	 INVENTORY 		NUMBER(4), 
	 CAT_ID 		VARCHAR2(4),
CONSTRAINT PK_PROD1 PRIMARY KEY (PROD_ID),
CONSTRAINT FK_PROD FOREIGN KEY (CAT_ID) REFERENCES PROD_CATEGORY (CAT_ID));

CREATE SYNONYM PRODUCTS FOR PRODUCT;


CREATE TABLE ORDERS 
	(ORDER_ID 	VARCHAR2(10), 
	 CUST_ID 	VARCHAR2(10), 
	 STATUS 	VARCHAR2(1), 
	 EMP_ID 	VARCHAR2(10), 
	 ORDER_DATE DATE ,
CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID),
CONSTRAINT FK_ORDER FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID));

CREATE OR REPLACE SYNONYM ORDERSS FOR ORDERS;


CREATE TABLE ORDER_ITEM 
	(ORDER_ID 	VARCHAR2(10), 
	 PROD_ID 	VARCHAR2(10),  
	 QUANTITY 	NUMBER(4), 
	 UNITPRICE 	NUMBER(20,2),
	 WAREHOUSE_ID VARCHAR2(3),
CONSTRAINT PK_ORDERITEM PRIMARY KEY (ORDER_ID,PROD_ID),
CONSTRAINT FK_OITEM_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
CONSTRAINT FK_OITEM_PROD FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID),
CONSTRAINT FK_OITEM_WARE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (WAREHOUSE_ID));

CREATE OR REPLACE SYNONYM ORDER_ITEMS FOR ORDER_ITEM;

--AUDIT TABLE
CREATE TABLE ORDER_LOG
	(ORDER_ID 	VARCHAR2(12),
	 MOD_NO 	NUMBER(2),
	 CHANGE_DATE DATE,
	 ACTION 	VARCHAR2(3),
CONSTRAINT PK_LOG PRIMARY KEY (ORDER_ID,MOD_NO));
