--THIS IS STUB FOR PLACING ORDER, HERE NUMBER OF ITEM CAN BE ADDED WITH ORDER_ITEMS_INS CALL
DECLARE
	L_ORD VARCHAR2(12);
	L_PRD VARCHAR2(10);
	L_QUAN NUMBER(4);
	L_PRICE NUMBER(20,2);
	L_WARE VARCHAR2(3);
	L_CONT NUMBER;
BEGIN
	
	BEGIN
		SELECT 	LPAD(TO_NUMBER(MAX(ORDER_ID))+1,6,0) 
		INTO 	L_ORD 
		FROM 	ORDERSS;
	EXCEPTION WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('FAILE WHILE SELECTING ORDER ID');
	END;
	ONLINE_STORE.ORDERSS_INS(L_ORD,'CU001','P','E004',TO_DATE(SYSDATE,'DD-MM-YYYY'));
	ONLINE_STORE.ORDER_ITEMS_INS(L_ORD,'P0004',2,130,'W01');
	ONLINE_STORE.ORDER_ITEMS_INS(L_ORD,'P0006',2,130,'W03');
	ONLINE_STORE.ORDER_ITEMS_INS(L_ORD,'P0007',2,130,'W04');
	ONLINE_STORE.ORDER_ITEMS_INS(L_ORD,'P0008',2,130,'W05');

EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('FAILED PLACING ORDER'||SQLERRM);

END ;
/
COMMIT;

