create table Department_bkup as  select * from Departments;
create table Region_bkup as select * from Regions;
create table country_bkup as select * from countrys;
create table Warehouse_bkup as select * from Warehouses;
create table Location_bkup as select * from Locations;
create table Employee_bkup as select * from Employees;
create table Cust_Contact_bkup as select * from Cust_Contacts;
create table Customer_bkup as select * from Customers;
create table Prod_category_bkup as select * from Prod_categorys;
create table Product_bkup as select * from Products;
create table Orders_bkup as select * from Orderss  ;
create table Order_item_bkup as select * from Order_items ;
