--WITH THIS STUB, WE CAN DELETE ORDER WHICH IS STILL PENDING STATUS
--IF STATUS IS SHIPPED/DELIVERED THEN DELETION NOT POSSIBLE
DECLARE
	L_ORD_STATUS VARCHAR2(1);
	L_ORD		 VARCHAR2(12);
BEGIN
	L_ORD := '&DELETE_ORDERNUMBER';
	BEGIN
		SELECT STATUS 
		INTO L_ORD_STATUS 
		FROM ORDERSS 
		WHERE ORDER_ID =L_ORD;
	EXCEPTION WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('FAILE WHILE SELECTING ORDER STATUS');
	END;	
	IF L_ORD_STATUS ='P' THEN
	DELETE FROM ORDER_ITEMS WHERE ORDER_ID =L_ORD;
	DELETE FROM ORDERSS WHERE ORDER_ID =L_ORD;
	ELSE
	  DBMS_OUTPUT.PUT_LINE('ORDER ALREDY SHIPED OR DELIVERED, CAN NOT DELETE');
	END IF;
EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('FAILE WHILE DELETEING ORDER ID'||SQLERRM);
		
END ;
/
COMMIT;
